spring.application.name=GestorEstoquesWeb
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/gestor_estoque
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.security.enabled=false
app.jwt.secret=VGhpc0lzQVNlY3VyZUpXVFNlY3JldEtleUZvckRldk9ubHlFeGFtcGxlMTIzNDU2Nzg5MA==
app.jwt.expiration-ms=28800000
app.jwt.cookie-name=GESTOR_AUTH
