/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgestorestoque.Frames;

import AppGestorEstoques.Model.Fornecedor;
import AppGestorEstoques.Model.Produto;
import AppGestorEstoques.Model.User;
import AppGestorEstoques.Service.FornecedorService;
import AppGestorEstoques.Service.ProdutoService;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author Ericz
 */
public class CadProdutosView extends javax.swing.JFrame {

    private User user;
    private final ProdutoService PdService;
    private final FornecedorService fornecedorService;


    /**
     * Creates new form CadProdutosView
     */
    public CadProdutosView() {
        this(new ProdutoService(), new FornecedorService());
    }

    public CadProdutosView(ProdutoService produtoService, FornecedorService fornecedorService) {
        this.PdService = produtoService;
        this.fornecedorService = fornecedorService;
        initComponents();
        this.setTitle("Cadastro de Produtos - Gestor Estoques");
        this.setResizable(false);

        txt_produtosNome.setText("Insira o nome do produto");
        txt_produtosNome.setForeground(Color.BLACK);

        txt_produtosCodigo.setText("Insira o código do produto");
        txt_produtosCodigo.setForeground(Color.BLACK);

        txt_produtosCompra.setText("Insira o preco de compra");
        txt_produtosCompra.setForeground(Color.BLACK);

        txt_produtosVenda.setText("Insira o preco de venda");
        txt_produtosVenda.setForeground(Color.BLACK);

        txt_produtosValidade.setText("Insira o prazo de validade");
        txt_produtosValidade.setForeground(Color.BLACK);

        txt_produtosQuantidade.setText("Insira a quantidade");
        txt_produtosQuantidade.setForeground(Color.BLACK);

        carregarFornecedoresNoCombo();

    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btn_produtosCadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_produtosVoltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_produtosCompra = new javax.swing.JTextField();
        txt_produtosQuantidade = new javax.swing.JTextField();
        txt_produtosCodigo = new javax.swing.JTextField();
        txt_produtosNome = new javax.swing.JTextField();
        txt_produtosVenda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        combo_produtosFornecedor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_produtosValidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_produtosEditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_produtosExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("VALOR DE VENDA:");

        btn_produtosCadastrar.setBackground(new java.awt.Color(0, 255, 30));
        btn_produtosCadastrar.setText("CADASTRAR");
        btn_produtosCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produtosCadastrarActionPerformed(evt);
            }
        });

        jLabel6.setText("FORNECEDOR:");

        btn_produtosVoltar.setBackground(new java.awt.Color(0, 200, 0));
        btn_produtosVoltar.setText("VOLTAR");
        btn_produtosVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produtosVoltarActionPerformed(evt);
            }
        });

        jLabel7.setText("VALIDADE:");

        jLabel8.setText("QUANTIDADE:");

        txt_produtosCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_produtosCompraFocusLost(evt);
            }
        });
        txt_produtosCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_produtosCompraMousePressed(evt);
            }
        });

        txt_produtosQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_produtosQuantidadeFocusLost(evt);
            }
        });
        txt_produtosQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_produtosQuantidadeMousePressed(evt);
            }
        });
        txt_produtosQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_produtosQuantidadeActionPerformed(evt);
            }
        });

        txt_produtosCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_produtosCodigoFocusLost(evt);
            }
        });
        txt_produtosCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_produtosCodigoMousePressed(evt);
            }
        });

        txt_produtosNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_produtosNomeFocusLost(evt);
            }
        });
        txt_produtosNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_produtosNomeMousePressed(evt);
            }
        });
        txt_produtosNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_produtosNomeActionPerformed(evt);
            }
        });

        txt_produtosVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_produtosVendaFocusLost(evt);
            }
        });
        txt_produtosVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_produtosVendaMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CADASTRO DE PRODUTOS");

        jLabel2.setText("NOME:");

        txt_produtosValidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_produtosValidadeFocusLost(evt);
            }
        });
        txt_produtosValidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_produtosValidadeMousePressed(evt);
            }
        });

        jLabel3.setText("CÓDIGO:");

        btn_produtosEditar.setBackground(new java.awt.Color(0, 255, 255));
        btn_produtosEditar.setText("EDITAR");
        btn_produtosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produtosEditarActionPerformed(evt);
            }
        });

        jLabel4.setText("VALOR DE \nCOMPRA:");

        btn_produtosExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btn_produtosExcluir.setText("EXCLUIR");
        btn_produtosExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_produtosExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_produtosValidade, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(combo_produtosFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_produtosNome)
                            .addComponent(txt_produtosCodigo)
                            .addComponent(txt_produtosCompra)
                            .addComponent(txt_produtosVenda, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_produtosQuantidade)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_produtosCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn_produtosEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn_produtosExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btn_produtosVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_produtosNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_produtosCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_produtosCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_produtosVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_produtosFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_produtosValidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_produtosQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_produtosCadastrar)
                    .addComponent(btn_produtosEditar)
                    .addComponent(btn_produtosExcluir))
                .addGap(18, 18, 18)
                .addComponent(btn_produtosVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_produtosCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produtosCadastrarActionPerformed
        if(user==null){
            JOptionPane.showMessageDialog(this, "Erro na autenticacao de usuario!\nFaça login novamente.",
                    "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            FornecedorComboItem fornecedorSelecionado = (FornecedorComboItem) combo_produtosFornecedor.getSelectedItem();
            if (fornecedorSelecionado == null || fornecedorSelecionado.id() <= 0) {
                JOptionPane.showMessageDialog(this, "Selecione um fornecedor valido.",
                        "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            PdService.cadastrarProduto
                    (
                            user,
                            fornecedorSelecionado.id(),
                            txt_produtosNome.getText(),
                            txt_produtosCodigo.getText(),
                            txt_produtosQuantidade.getText(),
                            txt_produtosCompra.getText(),
                            txt_produtosVenda.getText(),
                            txt_produtosValidade.getText()
                    );
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            //limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_produtosCadastrarActionPerformed

    private void btn_produtosVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produtosVoltarActionPerformed
        MenuView menu = new MenuView();
        if (user != null) {
            menu.setUser(user);
        }
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_produtosVoltarActionPerformed

    private void txt_produtosCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_produtosCompraFocusLost
       if(txt_produtosCompra.getText().isEmpty()){
           txt_produtosCompra.setText("Insira o preco de compra");
       }
    }//GEN-LAST:event_txt_produtosCompraFocusLost

    private void txt_produtosCompraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_produtosCompraMousePressed
        if (txt_produtosCompra.getText().equals("Insira o preco de compra")) {
            txt_produtosCompra.setText("");
        }
    }//GEN-LAST:event_txt_produtosCompraMousePressed

    private void txt_produtosQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_produtosQuantidadeFocusLost
        if (txt_produtosQuantidade.getText().isEmpty()) {
            txt_produtosQuantidade.setText("Insira a quantidade");
        }
    }//GEN-LAST:event_txt_produtosQuantidadeFocusLost

    private void txt_produtosQuantidadeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_produtosQuantidadeMousePressed
        if (txt_produtosQuantidade.getText().equals("Insira a quantidade")) {
            txt_produtosQuantidade.setText("");
        }
    }//GEN-LAST:event_txt_produtosQuantidadeMousePressed

    private void txt_produtosQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_produtosQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_produtosQuantidadeActionPerformed

    private void txt_produtosCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_produtosCodigoFocusLost
        if (txt_produtosCodigo.getText().isEmpty()) {
            txt_produtosCodigo.setText("Insira o código do produto");
        }
    }//GEN-LAST:event_txt_produtosCodigoFocusLost

    private void txt_produtosCodigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_produtosCodigoMousePressed
        if (txt_produtosCodigo.getText().equals("Insira o código do produto")) {
            txt_produtosCodigo.setText("");
        }
    }//GEN-LAST:event_txt_produtosCodigoMousePressed

    private void txt_produtosNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_produtosNomeFocusLost
        if (txt_produtosNome.getText().isEmpty()) {
            txt_produtosNome.setText("Insira o nome do produto");
        }
    }//GEN-LAST:event_txt_produtosNomeFocusLost

    private void txt_produtosNomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_produtosNomeMousePressed
        if (txt_produtosNome.getText().equals("Insira o nome do produto")) {
            txt_produtosNome.setText("");
        }
    }//GEN-LAST:event_txt_produtosNomeMousePressed

    private void txt_produtosNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_produtosNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_produtosNomeActionPerformed

    private void txt_produtosVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_produtosVendaFocusLost
        if (txt_produtosVenda.getText().isEmpty()) {
            txt_produtosVenda.setText("Insira o preco de venda");
        }
    }//GEN-LAST:event_txt_produtosVendaFocusLost

    private void txt_produtosVendaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_produtosVendaMousePressed
        if (txt_produtosVenda.getText().equals("Insira o preco de venda")) {
            txt_produtosVenda.setText("");
        }
    }//GEN-LAST:event_txt_produtosVendaMousePressed

    private void txt_produtosValidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_produtosValidadeFocusLost
        if (txt_produtosValidade.getText().isEmpty()) {
            txt_produtosValidade.setText("Insira o prazo de validade");
        }
    }//GEN-LAST:event_txt_produtosValidadeFocusLost

    private void txt_produtosValidadeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_produtosValidadeMousePressed
        if (txt_produtosValidade.getText().equals("Insira o prazo de validade")) {
            txt_produtosValidade.setText("");
        }
    }//GEN-LAST:event_txt_produtosValidadeMousePressed

    private void btn_produtosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produtosEditarActionPerformed
        try {
            String searchInput = JOptionPane.showInputDialog(this,
                    "Insira o codigo, nome ou ID do produto a editar:",
                    "Buscar Produto", JOptionPane.QUESTION_MESSAGE);
            if (searchInput == null || searchInput.trim().isEmpty()) {
                return;
            }

            Produto produto = PdService.buscarProduto(searchInput.trim());
            if (produto == null) {
                JOptionPane.showMessageDialog(this,
                        "Produto '" + searchInput + "' nao encontrado.",
                        "Produto nao encontrado", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String nomeProduto = JOptionPane.showInputDialog(this, "Nome do Produto:", produto.nomeProduto());
            if (nomeProduto == null) return;
            String codigoProduto = JOptionPane.showInputDialog(this, "Codigo do Produto:", produto.codigoProduto());
            if (codigoProduto == null) return;
            String quantidadeStr = JOptionPane.showInputDialog(this, "Quantidade em Estoque:", String.valueOf(produto.quantidadeEstoque()));
            if (quantidadeStr == null) return;
            String valorCompraStr = JOptionPane.showInputDialog(this, "Valor de Compra (ex: 10.50):", produto.valorCompra().toString());
            if (valorCompraStr == null) return;
            String valorVendaStr = JOptionPane.showInputDialog(this, "Valor de Venda (ex: 15.50):", produto.valorVenda().toString());
            if (valorVendaStr == null) return;
            String validadeStr = JOptionPane.showInputDialog(this, "Validade (yyyy-MM-dd):", produto.validadeProduto().toString());
            if (validadeStr == null) return;
            String idFornecedorStr = JOptionPane.showInputDialog(this, "ID do Fornecedor:", String.valueOf(produto.idFornecedor()));
            if (idFornecedorStr == null) return;

            PdService.editarProduto(
                    searchInput.trim(),
                    nomeProduto,
                    codigoProduto,
                    quantidadeStr,
                    valorCompraStr,
                    valorVendaStr,
                    validadeStr,
                    idFornecedorStr
            );

            JOptionPane.showMessageDialog(this,
                    "Produto atualizado com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            txt_produtosNome.setText("Insira o nome do produto");
            txt_produtosCodigo.setText("Insira o codigo do produto");
            txt_produtosCompra.setText("Insira o preco de compra");
            txt_produtosVenda.setText("Insira o preco de venda");
            combo_produtosFornecedor.setSelectedIndex(combo_produtosFornecedor.getItemCount() > 0 ? 0 : -1);
            txt_produtosValidade.setText("Insira o prazo de validade");
            txt_produtosQuantidade.setText("Insira a quantidade");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao editar: " + e.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_produtosEditarActionPerformed

    private void btn_produtosExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_produtosExcluirActionPerformed
        try {
            String searchInput = JOptionPane.showInputDialog(this,
                    "Insira o código, nome ou ID do produto a deletar:",
                    "Buscar Produto", JOptionPane.QUESTION_MESSAGE);

            if (searchInput == null || searchInput.trim().isEmpty()) {
                return; // User cancelled
            }

            Produto produto = PdService.buscarProduto(searchInput.trim());

            if (produto == null) {
                JOptionPane.showMessageDialog(this,
                        "Produto '" + searchInput + "' não encontrado.",
                        "Produto não encontrado", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Confirm deletion
            int confirmacao = JOptionPane.showConfirmDialog(this,
                    "Tem certeza que deseja deletar o produto:\n" +
                    "Nome: " + produto.nomeProduto() + "\n" +
                    "Código: " + produto.codigoProduto() + "\n" +
                    "ID: " + produto.idProduto() + "\n\n" +
                    "Esta ação não pode ser desfeita!",
                    "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (confirmacao != JOptionPane.YES_OPTION) {
                return; // User cancelled
            }

            PdService.excluirProdutoPorId(produto.idProduto());

            JOptionPane.showMessageDialog(this,
                    "Produto deletado com sucesso!",
                    "Exclusão", JOptionPane.INFORMATION_MESSAGE);

            // Clear fields
            txt_produtosNome.setText("Insira o nome do produto");
            txt_produtosCodigo.setText("Insira o código do produto");
            txt_produtosCompra.setText("Insira o preco de compra");
            txt_produtosVenda.setText("Insira o preco de venda");
            combo_produtosFornecedor.setSelectedIndex(combo_produtosFornecedor.getItemCount() > 0 ? 0 : -1);
            txt_produtosValidade.setText("Insira o prazo de validade");
            txt_produtosQuantidade.setText("Insira a quantidade");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao deletar: " + e.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btn_produtosExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    private void carregarFornecedoresNoCombo() {
        combo_produtosFornecedor.removeAllItems();
        List<Fornecedor> fornecedores = fornecedorService.listarTodos();
        for (Fornecedor fornecedor : fornecedores) {
            combo_produtosFornecedor.addItem(new FornecedorComboItem(
                    fornecedor.idFornecedor(),
                    fornecedor.nomeFornecedor()
            ));
        }
        if (combo_produtosFornecedor.getItemCount() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Nenhum fornecedor cadastrado. Cadastre um fornecedor antes de cadastrar produtos.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    private record FornecedorComboItem(int id, String nome) {
        @Override
        public String toString() {
            return nome;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_produtosCadastrar;
    private javax.swing.JButton btn_produtosEditar;
    private javax.swing.JButton btn_produtosExcluir;
    private javax.swing.JButton btn_produtosVoltar;
    private javax.swing.JComboBox<FornecedorComboItem> combo_produtosFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_produtosCodigo;
    private javax.swing.JTextField txt_produtosCompra;
    private javax.swing.JTextField txt_produtosNome;
    private javax.swing.JTextField txt_produtosQuantidade;
    private javax.swing.JTextField txt_produtosValidade;
    private javax.swing.JTextField txt_produtosVenda;
    // End of variables declaration//GEN-END:variables
}
