/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgestorestoque.Frames;

import AppGestorEstoques.Model.UserProfile;
import AppGestorEstoques.Model.User;
import AppGestorEstoques.Model.UserRegistrationData;
import AppGestorEstoques.Model.UserUpdateData;
import AppGestorEstoques.Service.IUserManagementService;
import AppGestorEstoques.Service.UserManagementService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Ericz
 */
public class GestaoUserView extends javax.swing.JFrame {

    private User user;
    private final IUserManagementService userManagementService;
    private final List<UserProfile> usuarios = new ArrayList<>();
    private DefaultTableModel tableModel;
    private TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form GestaoUserView
     */
    public GestaoUserView() {
        this(new UserManagementService());
    }

    public GestaoUserView(IUserManagementService userManagementService) {
        this.userManagementService = userManagementService;
        initComponents();
        this.setTitle("Gestao de usuarios - Gestor Estoque");
        this.setResizable(false);
        initTabela();
        carregarUsuarios();
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboFiltro = new javax.swing.JComboBox<>();
        btn_deleteUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableGestao = new javax.swing.JTable();
        btn_userAdd = new javax.swing.JButton();
        btn_userEdit = new javax.swing.JButton();
        btn_menuVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Administrador", "Gestor", "Operador de estoque" }));
        comboFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFiltroActionPerformed(evt);
            }
        });

        btn_deleteUser.setBackground(new java.awt.Color(255, 0, 0));
        btn_deleteUser.setText("EXCLUIR USUÁRIO");
        btn_deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteUserActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("GESTÃO DE USUÁRIOS");

        tableGestao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"NOME", "ACESSO", "DETALHES"}
        ));
        jScrollPane2.setViewportView(tableGestao);

        btn_userAdd.setBackground(new java.awt.Color(0, 255, 30));
        btn_userAdd.setText("ADICIONAR USUÁRIO");
        btn_userAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userAddActionPerformed(evt);
            }
        });

        btn_userEdit.setBackground(new java.awt.Color(0, 255, 255));
        btn_userEdit.setText("EDITAR USUÁRIO");
        btn_userEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userEditActionPerformed(evt);
            }
        });

        btn_menuVoltar.setBackground(new java.awt.Color(0, 255, 0));
        btn_menuVoltar.setText("VOLTAR");
        btn_menuVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btn_userAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_deleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_userEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_menuVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_menuVoltar)
                    .addComponent(comboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_userEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btn_deleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_userAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroActionPerformed
        aplicarFiltroPerfil();
    }//GEN-LAST:event_comboFiltroActionPerformed

    private void btn_deleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteUserActionPerformed
        String criterio = JOptionPane.showInputDialog(this,
                "Informe o ID ou nome do usuario para excluir:",
                "Excluir Usuario",
                JOptionPane.QUESTION_MESSAGE);

        if (criterio == null || criterio.trim().isEmpty()) {
            return;
        }

        try {
            UserProfile alvo = userManagementService.buscarPorIdOuNome(criterio);
            if (alvo == null) {
                JOptionPane.showMessageDialog(this, "Usuario nao encontrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int confirmacao = JOptionPane.showConfirmDialog(this,
                    "Deseja excluir o usuario '" + alvo.nome() + "' (ID " + alvo.id() + ")?",
                    "Confirmar exclusao",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirmacao != JOptionPane.YES_OPTION) {
                return;
            }

            userManagementService.excluirPorIdOuNome(criterio);
            carregarUsuarios();
            JOptionPane.showMessageDialog(this, "Usuario excluido com sucesso.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_deleteUserActionPerformed

    private void btn_userAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userAddActionPerformed
        UserFormDialog dialog = new UserFormDialog(this, "Cadastrar Usuario", null);
        dialog.setVisible(true);
        if (!dialog.isConfirmado()) {
            return;
        }

        try {
            userManagementService.cadastrarUsuario(new UserRegistrationData(
                    dialog.getNome(),
                    dialog.getEmail(),
                    dialog.getSenha(),
                    dialog.getPerfil(),
                    dialog.isAtivo()
            ));
            carregarUsuarios();
            JOptionPane.showMessageDialog(this, "Usuario cadastrado com sucesso.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_userAddActionPerformed

    private void btn_userEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userEditActionPerformed
        String criterio = JOptionPane.showInputDialog(this,
                "Informe o ID ou nome do usuario para editar:",
                "Editar Usuario",
                JOptionPane.QUESTION_MESSAGE);

        if (criterio == null || criterio.trim().isEmpty()) {
            return;
        }

        try {
            UserProfile alvo = userManagementService.buscarPorIdOuNome(criterio);
            if (alvo == null) {
                JOptionPane.showMessageDialog(this, "Usuario nao encontrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            UserFormDialog dialog = new UserFormDialog(this, "Editar Usuario", alvo);
            dialog.setVisible(true);
            if (!dialog.isConfirmado()) {
                return;
            }

            userManagementService.atualizarUsuario(new UserUpdateData(
                    alvo.id(),
                    dialog.getNome(),
                    dialog.getEmail(),
                    dialog.getSenha(),
                    dialog.getPerfil(),
                    dialog.isAtivo()
            ));
            carregarUsuarios();
            JOptionPane.showMessageDialog(this, "Usuario atualizado com sucesso.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_userEditActionPerformed

    private void btn_menuVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuVoltarActionPerformed
        MenuView menu = new MenuView();
        if (user != null) {
            menu.setUser(user);
        }
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_menuVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestaoUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestaoUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestaoUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestaoUserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deleteUser;
    private javax.swing.JButton btn_menuVoltar;
    private javax.swing.JButton btn_userAdd;
    private javax.swing.JButton btn_userEdit;
    private javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableGestao;
    // End of variables declaration//GEN-END:variables

    private void initTabela() {
        tableModel = new DefaultTableModel(new Object[]{"Nome", "Perfil"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 1;
            }
        };
        tableGestao.setModel(tableModel);
        tableGestao.setRowHeight(32);

        sorter = new TableRowSorter<>(tableModel);
        tableGestao.setRowSorter(sorter);

        tableGestao.getColumnModel().getColumn(1).setCellRenderer(new PerfilButtonRenderer());
        tableGestao.getColumnModel().getColumn(1).setCellEditor(new PerfilButtonEditor(new JCheckBox()));
    }

    private void carregarUsuarios() {
        try {
            usuarios.clear();
            usuarios.addAll(userManagementService.listarUsuarios());

            tableModel.setRowCount(0);
            for (UserProfile item : usuarios) {
                tableModel.addRow(new Object[]{item.nome(), "VER PERFIL"});
            }

            aplicarFiltroPerfil();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void aplicarFiltroPerfil() {
        if (sorter == null) {
            return;
        }

        String filtro = (String) comboFiltro.getSelectedItem();
        if (filtro == null || "Todos".equalsIgnoreCase(filtro)) {
            sorter.setRowFilter(null);
            return;
        }

        sorter.setRowFilter(new RowFilter<>() {
            @Override
            public boolean include(Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                int modelRow = entry.getIdentifier();
                if (modelRow < 0 || modelRow >= usuarios.size()) {
                    return false;
                }

                String perfil = usuarios.get(modelRow).perfil();
                return perfil != null && perfil.equalsIgnoreCase(filtro);
            }
        });
    }

    private void mostrarPerfilCompleto(int viewRow) {
        if (viewRow < 0) {
            return;
        }

        int modelRow = tableGestao.convertRowIndexToModel(viewRow);
        if (modelRow < 0 || modelRow >= usuarios.size()) {
            return;
        }

        UserDetailsDialog dialog = new UserDetailsDialog(this, usuarios.get(modelRow));
        dialog.setVisible(true);
    }

    class PerfilButtonRenderer extends JButton implements TableCellRenderer {
        public PerfilButtonRenderer() {
            setOpaque(true);
            setText("VER PERFIL");
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            setText(value == null ? "VER PERFIL" : value.toString());
            return this;
        }
    }

    class PerfilButtonEditor extends DefaultCellEditor {
        private final JButton button;
        private int selectedRow = -1;
        private String label;

        public PerfilButtonEditor(JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
            button.setOpaque(true);
            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped();
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            selectedRow = row;
            label = value == null ? "VER PERFIL" : value.toString();
            button.setText(label);
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            mostrarPerfilCompleto(selectedRow);
            return label;
        }
    }
}


