/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgestorestoque.Frames;

import AppGestorEstoques.Infra.Conexao;
import AppGestorEstoques.Service.ILoginService;
import AppGestorEstoques.Service.LoginService;
import AppGestorEstoques.Model.User;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Ericz
 */
public class LoginView extends javax.swing.JFrame {

    private final ILoginService loginService;
    private char defaultEchoChar;
    private boolean passPlaceholderActive = false;

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        this(new LoginService(new Conexao()));
    }

    public LoginView(ILoginService loginService) {
        this.loginService = loginService;
        initComponents();
        this.setTitle("Login - Gestor Estoques");
        this.setResizable(false);


        txt_user.setText("Insira seu usuário");
        txt_user.setForeground(Color.BLACK);

        // Preserve LAF echo char (the masked char used by the current LAF)
        defaultEchoChar = txt_pass.getEchoChar();

        // Setup placeholder for password field: show plain text and disable the
        // visibility checkbox until the user types a real password.
        passPlaceholderActive = true;
        txt_pass.setText("Insira sua senha");
        txt_pass.setForeground(Color.BLACK);
        txt_pass.setEchoChar((char) 0); // show placeholder text
        turnVisibleBox.setSelected(false);
        turnVisibleBox.setEnabled(false);

        // Enable the visibility checkbox when the user types something that is
        // not the placeholder. Use a document listener so it reacts to typing/paste.
        txt_pass.getDocument().addDocumentListener(new DocumentListener() {
            private void update() {
                String current = new String(txt_pass.getPassword());
                boolean hasReal = !current.isEmpty() && !passPlaceholderActive;
                // If placeholder is active but user typed (some LAFs may keep it),
                // consider that typing cleared it via focusGained handler.
                turnVisibleBox.setEnabled(hasReal);
            }
            @Override public void insertUpdate(DocumentEvent e) { update(); }
            @Override public void removeUpdate(DocumentEvent e) { update(); }
            @Override public void changedUpdate(DocumentEvent e) { update(); }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        msg_erro = new javax.swing.JLabel();
        turnVisibleBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USUÁRIO:");

        txt_user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_user.setActionCommand("<Not Set>");
        txt_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_userFocusLost(evt);
            }
        });
        txt_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_userMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_userMousePressed(evt);
            }
        });
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SENHA:");

        txt_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passFocusLost(evt);
            }
        });
        txt_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_passMousePressed(evt);
            }
        });
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(0, 255, 0));
        btn_login.setText("ENTRAR");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        msg_erro.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        msg_erro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        turnVisibleBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnVisibleBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(turnVisibleBox)
                                .addGap(84, 84, 84))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(msg_erro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_login)
                        .addGap(18, 18, 18)
                        .addComponent(msg_erro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(turnVisibleBox))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_userFocusGained

    }//GEN-LAST:event_txt_userFocusGained

    private void txt_userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_userFocusLost
        if (txt_user.getText().isEmpty()) {
            txt_user.setText("Insira seu usuário");
            txt_user.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_userFocusLost

    private void txt_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userMouseClicked

    }//GEN-LAST:event_txt_userMouseClicked

    private void txt_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userMousePressed
        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (txt_user.getText().equals("Insira seu usuário")) {
                txt_user.setText("");
                txt_user.setForeground(Color.BLACK);
            }
        }
    }//GEN-LAST:event_txt_userMousePressed

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void txt_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passFocusLost
        // If the field is empty after losing focus, restore the placeholder.
        String current = new String(txt_pass.getPassword());
        if (current.isEmpty()) {
            passPlaceholderActive = true;
            txt_pass.setText("Insira sua senha");
            txt_pass.setForeground(Color.GRAY);
            txt_pass.setEchoChar((char) 0);
            turnVisibleBox.setEnabled(false);
        }
    }//GEN-LAST:event_txt_passFocusLost

    private void txt_passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passMousePressed
        // No placeholder logic for password field
    }//GEN-LAST:event_txt_passMousePressed

    private void txt_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passFocusGained
        // If placeholder text is shown, clear it when the user focuses the field
        if (passPlaceholderActive) {
            passPlaceholderActive = false;
            txt_pass.setText("");
            txt_pass.setForeground(Color.BLACK);
            txt_pass.setEchoChar(defaultEchoChar);
            // After clearing placeholder, the document listener will enable the checkbox when the user types
            turnVisibleBox.setEnabled(false);
        }
    }//GEN-LAST:event_txt_passFocusGained

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String user = txt_user.getText();
        String pass = new String(txt_pass.getPassword());

        if ("Insira seu usuário".equals(user)) {
            user = "";
        }
        // If placeholder is active, treat password as empty
        if (passPlaceholderActive) {
            pass = "";
        }

        if (user == null || user.trim().isEmpty() || pass.trim().isEmpty()) {
            msg_erro.setText("Preencha usuario e senha.");
            msg_erro.setForeground(Color.RED);
            return;
        }

        try {
            User usuario = loginService.autenticar(user.trim(), pass);
            if (usuario == null) {
                msg_erro.setText("Usuario ou senha incorretos!");
                msg_erro.setForeground(Color.RED);
                return;
            }

            msg_erro.setText("");
            MenuView menu = new MenuView();
            menu.setUser(usuario);
            menu.setVisible(true);
            this.dispose();
        } catch (IllegalStateException e) {
            msg_erro.setText("Usuario inativo!");
            msg_erro.setForeground(Color.RED);
        } catch (SQLException e) {
            msg_erro.setText("Erro no servidor!");
            msg_erro.setForeground(Color.RED);
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void turnVisibleBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnVisibleBoxActionPerformed
        if (turnVisibleBox.isSelected()) {
            txt_pass.setEchoChar((char) 0);
        } else {
            txt_pass.setEchoChar(defaultEchoChar);
        }
    }//GEN-LAST:event_turnVisibleBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel msg_erro;
    private javax.swing.JCheckBox turnVisibleBox;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
