/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appgestorestoque.Frames;

import AppGestorEstoques.Model.User;
import AppGestorEstoques.Service.MovimentacaoService;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Ericz
 */
public class MovimentacoesView extends javax.swing.JFrame {

    private User user;
    private final MovimentacaoService movimentacao;

    /**
     * Creates new form MovimentacoesView
     */
    public MovimentacoesView() {
        this(new MovimentacaoService());
    }

    public MovimentacoesView(MovimentacaoService movimentacaoService) {
        this.movimentacao = movimentacaoService;
        initComponents();
        this.setTitle("Movimentações - Gestor Estoque");
        this.setSize(450,350);
        this.setResizable(false);

        txt_movimentacoesTipo.setText("Entrada / Saida / Ajuste");
        txt_movimentacoesTipo.setForeground(Color.BLACK);

        txt_movimentacoesProduto.setText("Insira o nome do produto movimentado");
        txt_movimentacoesProduto.setForeground(Color.BLACK);

        txt_movimentacoesQuantidade.setText("Insira a quantidade de produtos movimentada");
        txt_movimentacoesQuantidade.setForeground(Color.BLACK);
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txt_movimentacoesTipo = new javax.swing.JTextField();
        txt_movimentacoesProduto = new javax.swing.JTextField();
        txt_movimentacoesQuantidade = new javax.swing.JTextField();
        btn_movimentacoesRegistrar = new javax.swing.JButton();
        btn_movimentacoesCancel = new javax.swing.JButton();
        btn_movimentacoesVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("QUANTIDADE:");

        txt_movimentacoesTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_movimentacoesTipoFocusLost(evt);
            }
        });
        txt_movimentacoesTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_movimentacoesTipoMousePressed(evt);
            }
        });

        txt_movimentacoesProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_movimentacoesProdutoFocusLost(evt);
            }
        });
        txt_movimentacoesProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_movimentacoesProdutoMousePressed(evt);
            }
        });

        txt_movimentacoesQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_movimentacoesQuantidadeFocusLost(evt);
            }
        });
        txt_movimentacoesQuantidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_movimentacoesQuantidadeMousePressed(evt);
            }
        });

        btn_movimentacoesRegistrar.setBackground(new java.awt.Color(0, 255, 30));
        btn_movimentacoesRegistrar.setText("REGISTRAR");
        btn_movimentacoesRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_movimentacoesRegistrarActionPerformed(evt);
            }
        });

        btn_movimentacoesCancel.setBackground(new java.awt.Color(255, 0, 0));
        btn_movimentacoesCancel.setText("CANCELAR");
        btn_movimentacoesCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_movimentacoesCancelActionPerformed(evt);
            }
        });

        btn_movimentacoesVoltar.setBackground(new java.awt.Color(0, 200, 0));
        btn_movimentacoesVoltar.setText("VOLTAR");
        btn_movimentacoesVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_movimentacoesVoltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("MOVIMENTAÇÕES");

        jLabel2.setText("TIPO DE MOVIMENTAÇÃO:");

        jLabel3.setText("PRODUTO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_movimentacoesRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_movimentacoesCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_movimentacoesVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_movimentacoesTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txt_movimentacoesProduto)
                            .addComponent(txt_movimentacoesQuantidade))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_movimentacoesTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_movimentacoesProduto)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_movimentacoesQuantidade)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_movimentacoesRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_movimentacoesCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_movimentacoesVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_movimentacoesTipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_movimentacoesTipoFocusLost
        if (txt_movimentacoesTipo.getText().isEmpty()) {
            txt_movimentacoesTipo.setText("Entrada / Saida / Ajuste");
            txt_movimentacoesTipo.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_movimentacoesTipoFocusLost

    private void txt_movimentacoesTipoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_movimentacoesTipoMousePressed
        if (txt_movimentacoesTipo.getText().equals("Entrada / Saida / Ajuste")) {
            txt_movimentacoesTipo.setText("");
        }
    }//GEN-LAST:event_txt_movimentacoesTipoMousePressed

    private void txt_movimentacoesProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_movimentacoesProdutoFocusLost
        if (txt_movimentacoesProduto.getText().isEmpty()) {
            txt_movimentacoesProduto.setText("Insira o nome do produto movimentado");
            txt_movimentacoesProduto.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_movimentacoesProdutoFocusLost

    private void txt_movimentacoesProdutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_movimentacoesProdutoMousePressed
        if (txt_movimentacoesProduto.getText().equals("Insira o nome do produto movimentado")) {
            txt_movimentacoesProduto.setText("");
        }
    }//GEN-LAST:event_txt_movimentacoesProdutoMousePressed

    private void txt_movimentacoesQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_movimentacoesQuantidadeFocusLost
        if (txt_movimentacoesQuantidade.getText().isEmpty()) {
            txt_movimentacoesQuantidade.setText("Insira a quantidade de produtos movimentada");
            txt_movimentacoesQuantidade.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_movimentacoesQuantidadeFocusLost

    private void txt_movimentacoesQuantidadeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_movimentacoesQuantidadeMousePressed
        if (txt_movimentacoesQuantidade.getText().equals("Insira a quantidade de produtos movimentada")) {
            txt_movimentacoesQuantidade.setText("");
        }
    }//GEN-LAST:event_txt_movimentacoesQuantidadeMousePressed

    private void btn_movimentacoesRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_movimentacoesRegistrarActionPerformed
        try {
            String tipoMovimentacao = txt_movimentacoesTipo.getText();
            String quantidade = txt_movimentacoesQuantidade.getText();

            movimentacao.registrarMovimentacao(user, quantidade, tipoMovimentacao);

            JOptionPane.showMessageDialog(this, "Movimentacao registrado com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_movimentacoesRegistrarActionPerformed

    private void btn_movimentacoesCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_movimentacoesCancelActionPerformed
        try {
            if (user == null) {
                JOptionPane.showMessageDialog(this,
                        "Erro na autenticacao de usuario!\nFaca login novamente.",
                        "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int confirmacao = JOptionPane.showConfirmDialog(this,
                    "Deseja cancelar a ultima movimentacao registrada?",
                    "Confirmar cancelamento",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirmacao != JOptionPane.YES_OPTION) {
                return;
            }

            movimentacao.cancelarUltimaMovimentacao(user);

            JOptionPane.showMessageDialog(this,
                    "Ultima movimentacao cancelada com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_movimentacoesCancelActionPerformed

    private void btn_movimentacoesVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_movimentacoesVoltarActionPerformed
        MenuView menu = new MenuView();
        if (user != null) {
            menu.setUser(user);
        }
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_movimentacoesVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimentacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimentacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimentacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimentacoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_movimentacoesCancel;
    private javax.swing.JButton btn_movimentacoesRegistrar;
    private javax.swing.JButton btn_movimentacoesVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_movimentacoesProduto;
    private javax.swing.JTextField txt_movimentacoesQuantidade;
    private javax.swing.JTextField txt_movimentacoesTipo;
    // End of variables declaration//GEN-END:variables
}
